### ISSUE TITLE
There seems to be a typo in the ClusterRole binding of version 0.9.0 on the stable branch

### ISSUE THREAD

**Issue by jbiskur** [OT-CONTAINER-KIT/redis-operator#184]
Version: 0.9.0 - stable

the error is that the operator cannot access any of the redis resources in the cluster due to it being forbidden.

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
version 1.21.2 on EKS
</pre></details>

**What did you do?**

**What did you expect to see?**
A standalone cluster being created

**What did you see instead?**
Failed to create any cluster, operator logged out that it did not have permission to see any redis resources.

I had to manually add "-redis" and "-redisclusters" to the resources, it only added "-rediss"

**Comment by asure-king** [comment]
hey bro

download de helm files and replace with other image: v 0.10.0

---
redisOperator:
  name: redis-operator
  imageName: quay.io/opstree/redis-operator
  **imageTag: v0.10.0**
  imagePullPolicy: Always

resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 500Mi

replicas: 1

serviceAccountName: redis-operator

priorityClassName: ""
nodeSelector: {}
tolerateAllTaints: false
tolerations: []
affinity: {}

**Comment by davidcollom** [comment]
@jbiskur / @iamabhishek-dubey I believe this should now be resolved and as @asure-king mentions, the newer `v0.10.0` release resolves this issue.

**Comment by iamabhishek-dubey** [comment]
This is resolved as the helm chart is updated with the desired RBAC.

**Comment by MatteoJoliveau** [comment]
Sorry for the necrobump, but this is still an issue when installing 0.11 via [OLM](https://operatorhub.io/operator/redis-operator/stable/redis-operator.v0.11.0). We have to manually patch the ClusterRole which is not great.
