### ISSUE TITLE
No PDB in RedisCluster spec CRD.

### ISSUE THREAD

**Issue by thuban-arrakis** [OT-CONTAINER-KIT/redis-operator#246]
**What version of redis operator are you using?**

redis-operator v0.10.0

**Does this issue reproduce with the latest release?**

Yes.

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.12-gke.1500", GitCommit:"d32c0db9a3ccd0ac73b0b3abd0532505217b376e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:02Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1

</pre></details>

**What did you do?**
```
kubectl apply -f https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/master/example/disruption_budget/cluster.yaml
```

**What did you expect to see?**
```
rediscluster.redis.redis.opstreelabs.in/redis-cluster created
```
**What did you see instead?**
```
error: error validating "https://raw.githubusercontent.com/OT-CONTAINER-KIT/redis-operator/master/example/disruption_budget/cluster.yaml": error validating data: ValidationError(RedisCluster.spec): unknown field "pdb" in in.opstreelabs.redis.redis.v1beta1.RedisCluster.spec; if you choose to ignore these errors, turn validation off with --validate=false

kubectl explain RedisCluster.spec.   
KIND:     RedisCluster
VERSION:  redis.redis.opstreelabs.in/v1beta1

RESOURCE: spec <Object>

DESCRIPTION:
     RedisClusterSpec defines the desired state of RedisCluster

FIELDS:
   TLS	<Object>
     TLS Configuration for redis instances

   clusterSize	<integer> -required-

   kubernetesConfig	<Object> -required-
     KubernetesConfig will be the JSON struct for Basic Redis Config

   nodeSelector	<map[string]string>

   priorityClassName	<string>

   redisExporter	<Object>
     RedisExporter interface will have the information for redis exporter
     related stuff

   redisFollower	<Object>
     RedisFollower interface will have the redis follower configuration

   redisLeader	<Object>
     RedisLeader interface will have the redis leader configuration

   resources	<Object>
     ResourceRequirements describes the compute resource requirements.

   securityContext	<Object>
     PodSecurityContext holds pod-level security attributes and common container
     settings. Some fields are also present in container.securityContext. Field
     values of container.securityContext take precedence over field values of
     PodSecurityContext.

   sidecars	<[]Object>

   storage	<Object>
     Storage is the inteface to add pvc and pv support in redis

   tolerations	<[]Object>


```

**Comment by iamabhishek-dubey** [comment]
Fixed in https://github.com/OT-CONTAINER-KIT/helm-charts/commit/e048aebc17aaa79e9244135ad7315ce299d49ea8

**Comment by vsychov** [comment]
it's still not working in 0.10.2 helm chart, according to this example: 
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/example/disruption_budget/cluster.yaml
