### ISSUE TITLE
Openshift Redis Cluster not starting

### ISSUE THREAD

**Issue by d4fseeker** [OT-CONTAINER-KIT/redis-operator#69]
When installing the Redis-Operator 0.5 through Openshift OperatorHub and creating a mostly default Redius Cluster as proposed by the Operator, my pods start with the following message: (example for redis-master-0 )
```
mkdir: can't create directory '/opt/redis': Permission denied
/usr/bin/entrypoint.sh: line 21: /etc/redis/redis.conf: Permission denied
/usr/bin/entrypoint.sh: line 21: /etc/redis/redis.conf: Permission denied
sed: /data/nodes.conf: No such file or directory
/usr/bin/entrypoint.sh: line 52: /etc/redis/redis.conf: Permission denied
Starting redis service in cluster mode.....
11:C 19 May 2021 18:50:05.120 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
11:C 19 May 2021 18:50:05.120 # Redis version=6.2.1 bits=64, commit=00000000, modified=0, pid=11, just started
11:C 19 May 2021 18:50:05.120 # Configuration loaded
11:C 19 May 2021 18:50:05.120 * monotonic clock: POSIX clock_gettime
11:C 19 May 2021 18:50:05.121 * Running mode=standalone, port=6379.
11:C 19 May 2021 18:50:05.121 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
11:C 19 May 2021 18:50:05.121 # Server initialized
11:C 19 May 2021 18:50:05.121 * Ready to accept connections
```

The PVC is bound to a NFS PV and confirmed working read-write through the Pod terminal on /data.
However it does not seem to create any data, probably because the startup is flaky.

The amount of permission denied at the beginning for pod-internal files is surprising, as well as the "Running mode=standalone" when it clearly should start as a cluster as per a few lines higher. 

Running redis-cli > "cluster info", it returns:
ERR This instance has cluster support disabled

Openshift uses the group-permission (the executing user belongs to group root) for read-write access to pod files. 
I can confirm that /opt and /etc/redis/redis.conf are not group-writable, but I am unsure how to test/fix this on provided containers?

**Comment by iamabhishek-dubey** [comment]
```yaml
spec:
  containers:
  # specification of the pod's containers
  # ...
  securityContext:
    fsGroup: 1234
```

You can try to change the fsgroup using securityContext

**Comment by raghuiisc** [comment]
i am also facing same issue

root@rkota-k8s-1:~/redis-operator/helm-charts# kubectl logs redis-cluster-master-0 -c redis-cluster-master -n redis-operator
sed: /data/nodes.conf: No such file or directory
Running without persistence mode
Starting redis service in cluster mode.....
11:C 23 May 2021 17:01:45.322 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
11:C 23 May 2021 17:01:45.322 # Redis version=6.2.1, bits=64, commit=00000000, modified=0, pid=11, just started
11:C 23 May 2021 17:01:45.322 # Configuration loaded
11:M 23 May 2021 17:01:45.323 * monotonic clock: POSIX clock_gettime
11:M 23 May 2021 17:01:45.324 * No cluster configuration found, I'm ac146b6c3f3d24f535ca72feeb4e79809f999e5f
11:M 23 May 2021 17:01:45.327 * Running mode=cluster, port=6379.
11:M 23 May 2021 17:01:45.327 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
11:M 23 May 2021 17:01:45.327 # Server initialized
11:M 23 May 2021 17:01:45.328 * Ready to accept connections
root@rkota-k8s-1:~/redis-operator/helm-charts# kubectl logs redis-cluster-master-1 -c redis-cluster-master -n redis-operator
Running without persistence mode
sed: /data/nodes.conf: No such file or directory
Starting redis service in cluster mode.....
11:C 23 May 2021 17:02:15.375 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
11:C 23 May 2021 17:02:15.375 # Redis version=6.2.1, bits=64, commit=00000000, modified=0, pid=11, just started
11:C 23 May 2021 17:02:15.375 # Configuration loaded
11:M 23 May 2021 17:02:15.376 * monotonic clock: POSIX clock_gettime
11:M 23 May 2021 17:02:15.377 * No cluster configuration found, I'm 8f4f8ec752b58edde0ded98eb67eeb2eb9240010
11:M 23 May 2021 17:02:15.379 * Running mode=cluster, port=6379.
11:M 23 May 2021 17:02:15.379 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
11:M 23 May 2021 17:02:15.379 # Server initialized
11:M 23 May 2021 17:02:15.380 * Ready to accept connections

**Comment by iamabhishek-dubey** [comment]
This is fixed inside the redis image

**Comment by devopstales** [comment]
@iamabhishek-dubey This Issue is still exists in image `quay.io/opstree/redis:v7.0.5`. 

```shell
Redis is running without password which is not recommended
/usr/bin/entrypoint.sh: line 22: /etc/redis/redis.conf: Permission denied
/usr/bin/entrypoint.sh: line 32: /etc/redis/redis.conf: Permission denied
sed: /data/nodes.conf: No such file or directory
/usr/bin/entrypoint.sh: line 72: /etc/redis/redis.conf: Permission denied
Running without TLS mode
Starting redis service in cluster mode.....
10:C 16 Feb 2023 11:50:32.845 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
10:C 16 Feb 2023 11:50:32.845 # Redis version=7.0.5, bits=64, commit=00000000, modified=0, pid=10, just started
10:C 16 Feb 2023 11:50:32.845 # Configuration loaded
10:M 16 Feb 2023 11:50:32.847 * monotonic clock: POSIX clock_gettime
10:M 16 Feb 2023 11:50:32.849 * Running mode=standalone, port=6379.
10:M 16 Feb 2023 11:50:32.849 # Server initialized
10:M 16 Feb 2023 11:50:32.850 * Ready to accept connections
```
