### ISSUE TITLE
Helm Chart installation error

### ISSUE THREAD

**Issue by raghuiisc** [OT-CONTAINER-KIT/redis-operator#72]
I am getting below error when trying to bring up redis cluster as below

helm repo add ot-helm https://ot-container-kit.github.io/helm-charts/
helm upgrade redis-operator ot-helm/redis-operator --install --namespace redis-operator <<< This was success
helm upgrade redis-cluster ot-helm/redis-setup --set setupMode="cluster" --set cluster.size=3 --install --namespace redis-operator

Release "redis-cluster" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: Get "https://10.62.45.55:6443/apis/redis.redis.opstreelabs.in/v1beta1/namespaces/redis-operator/redis/redis": stream error: stream ID 85; INTERNAL_ERROR

**Comment by iamabhishek-dubey** [comment]
```
Release "redis-cluster" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: Get "https://10.62.45.55:6443/apis/redis.redis.opstreelabs.in/v1beta1/namespaces/redis-operator/redis/redis": stream error: stream ID 85; INTERNAL_ERROR
```
This indicates you have installed something manually in the system

**Comment by iamabhishek-dubey** [comment]
try using 
```
--set name=redis-cluster
```

**Comment by raghuiisc** [comment]
Getting the same error even with --set name=redis-cluster

root@rkota-nrtric:~/dep/tools/k8s/bin# helm3 upgrade redis-cluster ot-helm/redis-setup --set setupMode="cluster" --set name=redis-cluster --set cluster.size=3 --install --namespace redis-operator
Release "redis-cluster" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: Get "https://10.62.45.55:6443/apis/redis.redis.opstreelabs.in/v1beta1/namespaces/redis-operator/redis/redis-cluster": stream error: stream ID 85; INTERNAL_ERROR

To give u a complete picture i am trying to install this on open ran sc, first i bought up the kubernestes cluster with one one master node and bought up all other components as mentioned in 
https://wiki.o-ran-sc.org/display/GS/Near+Realtime+RIC+Installation <<< after step 3 i executed below steps on the same cluster

$ helm repo add ot-helm https://ot-container-kit.github.io/helm-charts/
$ helm upgrade redis-operator ot-helm/redis-operator --install --namespace redis-operator

successfully installed the redis-operator but when i executed the below command i am getting the error
root@rkota-nrtric:~/dep/tools/k8s/bin# kubectl get pods -A
NAMESPACE        NAME                                                         READY   STATUS      RESTARTS   AGE
kube-system      coredns-5644d7b6d9-c8kbm                                     1/1     Running     1          11d
kube-system      coredns-5644d7b6d9-wwfjw                                     1/1     Running     1          11d
kube-system      etcd-rkota-nrtric                                            1/1     Running     1          11d
kube-system      kube-apiserver-rkota-nrtric                                  1/1     Running     1          11d
kube-system      kube-controller-manager-rkota-nrtric                         1/1     Running     12         11d
kube-system      kube-flannel-ds-2wxvr                                        1/1     Running     1          11d
kube-system      kube-proxy-9n57p                                             1/1     Running     1          11d
kube-system      kube-scheduler-rkota-nrtric                                  1/1     Running     9          11d
redis-operator   redis-operator-cb88cfc9c-f7wnv                               1/1     Running     9          11d
ricinfra         deployment-tiller-ricxapp-d4f98ff65-nknnx                    1/1     Running     0          11d
ricinfra         tiller-secret-generator-xsjnz                                0/1     Completed   0          11d
ricplt           deployment-ricplt-a1mediator-66fcf76c66-5g5mx                1/1     Running     0          11d
ricplt           deployment-ricplt-appmgr-6fd6664755-8c4pj                    1/1     Running     0          11d
ricplt           deployment-ricplt-e2mgr-7b96cb84c8-7r8kg                     1/1     Running     0          11d
ricplt           deployment-ricplt-e2term-alpha-5f55b8474-tqc5c               1/1     Running     8          11d
ricplt           deployment-ricplt-jaegeradapter-76ddbf9c9-77qrf              1/1     Running     0          11d
ricplt           deployment-ricplt-o1mediator-d8b9fcdf-rxbj2                  1/1     Running     0          11d
ricplt           deployment-ricplt-rtmgr-6d559897d8-ngpvj                     1/1     Running     3          11d
ricplt           deployment-ricplt-submgr-7d8cf4c57b-h5rc7                    1/1     Running     0          11d
ricplt           deployment-ricplt-vespamgr-7458d9b5d-d7plq                   1/1     Running     0          11d
ricplt           deployment-ricplt-xapp-onboarder-5958856fc8-s7nmz            2/2     Running     0          11d
ricplt           r4-infrastructure-kong-6c7f6db759-xkhmv                      2/2     Running     2          11d
ricplt           r4-infrastructure-prometheus-alertmanager-75dff54776-84ghk   2/2     Running     0          11d
ricplt           r4-infrastructure-prometheus-server-5fd7695-qlsf2            1/1     Running     0          11d
ricplt           statefulset-ricplt-dbaas-server-0                            1/1     Running     0          11d
root@rkota-nrtric:~/dep/tools/k8s/bin# helm3 upgrade redis-cluster ot-helm/redis-setup --set setupMode="cluster" --set name=redis-cluster --set cluster.size=3 --install --namespace redis-operator
Release "redis-cluster" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: Get "https://10.62.45.55:6443/apis/redis.redis.opstreelabs.in/v1beta1/namespaces/redis-operator/redis/redis-cluster": stream error: stream ID 85; INTERNAL_ERROR

**Comment by iamabhishek-dubey** [comment]
Fixed in this https://github.com/OT-CONTAINER-KIT/helm-charts/commit/f5e81eab6d69ce10970792bf4497d8f77795b94a

Just change the name of the release.

**Comment by iamabhishek-dubey** [comment]
Also update the helm repo by `helm repo update`

**Comment by raghuiisc** [comment]
> 
> 
> Also update the helm repo by `helm repo update`

i am still facing the same issue. Now one more issue i am observing is i see 3 redis-operator pods which is strange
oot@rkota-nrtric:~/helm-charts# kubectl get pods -n redis-operator
NAME                              READY   STATUS    RESTARTS   AGE
redis-operator-64c7bb95b8-vpk8t   1/1     Running   0          4m42s
redis-operator-68cdbd95bc-cfl8k   1/1     Running   0          4m47s
redis-operator-cb88cfc9c-vjxfz    1/1     Running   0          4m5s

`
